'use strict';
const fs=require('node:fs'),path=require('node:path');
const repo=path.resolve(__dirname,'../..'),dir=path.join(repo,'build/protected'),target=path.join(dir,'worker');
const account=process.argv[2];if(!/^[a-f0-9]{32}$/.test(account||''))throw Error('Provide the confirmed Cloudflare account ID.');
fs.mkdirSync(target,{recursive:true});const inventory=JSON.parse(fs.readFileSync(path.join(dir,'inventory.json')));
fs.copyFileSync(path.join(__dirname,'worker.mjs'),path.join(target,'worker.mjs'));
fs.copyFileSync(path.join(__dirname,'r2-reader.mjs'),path.join(target,'r2-reader.mjs'));
fs.writeFileSync(path.join(target,'index.mjs'),`import {createWorker} from './worker.mjs';\nexport default createWorker(${JSON.stringify(fs.readFileSync(path.join(dir,'index.json'),'utf8'))},${JSON.stringify(inventory.objects)});\n`);
const storage=JSON.parse(fs.readFileSync(path.join(dir,'r2-verified.json')));
fs.writeFileSync(path.join(target,'wrangler.jsonc'),JSON.stringify({name:'gpt-live-avatar-downloads',account_id:account,main:'index.mjs',compatibility_date:'2026-09-14',workers_dev:true,preview_urls:false,observability:{enabled:false},...(account===storage.account?{r2_buckets:[{binding:'AVATAR_ASSETS',bucket_name:storage.bucket}]}:{vars:{R2_STORAGE_ACCOUNT:storage.account,R2_BUCKET:storage.bucket}})},null,2));
console.log('Prepared the download gateway. No account resources were changed.');
