// Explicit live-provider test: generated audio only, never the microphone.
'use strict';
const {app,BrowserWindow}=require('electron'),fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict'),cp=require('child_process');
if(!process.argv.includes('--live'))throw Error('Pass --live for provider requests.');
const repo=path.resolve(__dirname,'..'),out=repo+'/build/qa-agent-live',user=path.join(os.homedir(),'Library/Application Support/gpt-live-avatar');fs.mkdirSync(out+'/files',{recursive:true});app.setPath('userData',out+'/profile');fs.mkdirSync(app.getPath('userData')+'/avatars',{recursive:true});app.setName('gpt-live-avatar');
fs.copyFileSync(user+'/openai-key.bin',app.getPath('userData')+'/openai-key.bin');
fs.writeFileSync(app.getPath('userData')+'/config.json',JSON.stringify({avatar:'tia',quality:'friendly',agentEnabled:true,agentFolder:out+'/files',reasoningMode:'delegate',delegateProvider:'openai',delegateAuth:'codex_app_server'}));const tia=app.getPath('userData')+'/avatars/tia';if(!fs.existsSync(tia))fs.symlinkSync(repo+'/build/characters/tia',tia);
for(const f of ['codex-check.txt','hello.txt'])fs.rmSync(out+'/files/'+f,{force:true});
const spoken='Tia, please use your real file tools to create an empty test file named hello dot txt in the selected folder. Tell me after it has actually been created.';
cp.execFileSync('/usr/bin/say',['-v','Samantha','-o',out+'/question.aiff',spoken]);cp.execFileSync('/usr/bin/afconvert',[out+'/question.aiff',out+'/question.wav','-f','WAVE','-d','LEI16@24000']);
require('../electron/main.cjs');const wait=ms=>new Promise(r=>setTimeout(r,ms));async function until(fn,label,ms=90000){const end=Date.now()+ms;while(Date.now()<end){const v=await fn();if(v)return v;await wait(150);}throw Error('Timed out '+label);}
app.whenReady().then(async()=>{let win;try{win=await until(()=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/avatar.html')),'window');const js=s=>win.webContents.executeJavaScript('(async()=>{'+s+'})()');await until(()=>js('return window.gla_avatar?.resources?.ready'),'avatar');
 const codexResult=await js(`return await gla.agent.run({id:'codex-live-check',history:[{role:'user',text:'Create a file called codex-check.txt in the selected folder containing exactly: Native Codex tool call verified.'}]});`);assert(codexResult.ok,codexResult.error);assert.equal(fs.readFileSync(out+'/files/codex-check.txt','utf8').trim(),'Native Codex tool call verified.');console.log('Actual Codex agent created the file:',codexResult.model);
 await js(`await gla.setSettings({reasoningMode:'managed'});`);await wait(300);
 await js(`window.qaClock=new AudioContext();await qaClock.resume();window.qaDestination=qaClock.createMediaStreamDestination();window.qaSilence=qaClock.createConstantSource();qaSilence.offset.value=0;qaSilence.connect(qaDestination);qaSilence.start();Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:async()=>qaDestination.stream});window.qaError='';window.qaEvents=[];window.qaSent=[];window.qaAfterResult='';window.qaAfterResultAt=0;const send=gla_live.send.bind(gla_live);gla_live.send=e=>{qaSent.push(e);return send(e);};gla_live.addEventListener('error',({detail})=>qaError=detail.message);gla_live.addEventListener('event',({detail})=>{qaEvents.push({type:detail.type,id:detail.delegation?.id});if(detail.type==='session.output_transcript.delta'&&qaSent.some(e=>e.delegation_id)){qaAfterResult+=detail.delta||'';qaAfterResultAt=performance.now();}});await gla_live.start({voice:'marin',muted:false});`);
 await until(()=>js("return gla_live.state==='connected'||qaError"),'live voice');assert(!await js('return qaError'),await js('return qaError'));await wait(2200);
 const speech=fs.readFileSync(out+'/question.wav').toString('base64');await js(`const b=Uint8Array.from(atob('${speech}'),c=>c.charCodeAt(0));window.qaQuestion=qaClock.createBufferSource();qaQuestion.buffer=await qaClock.decodeAudioData(b.buffer);qaQuestion.connect(qaDestination);qaQuestion.start();`);
 await until(()=>fs.existsSync(out+'/files/hello.txt'),'spoken file action',90000);
 await until(()=>js(`return qaSent.some(e=>e.delegation_id&&/creat|saved|made/i.test(e.content))`),'verified result returned to voice',25000);
 await until(()=>js("return qaAfterResult.trim().length>6&&performance.now()-qaAfterResultAt>1500"),'spoken response after tool result',30000);
 const voice=await js('return {events:qaEvents,results:qaSent.filter(e=>e.delegation_id),history:gla_live.conversation(),spokenAfterResult:qaAfterResult,error:qaError};');assert(!voice.error,voice.error);fs.writeFileSync(out+'/report.json',JSON.stringify({passed:true,codex:codexResult,voice,fileBytes:fs.statSync(out+'/files/hello.txt').size},null,2));console.log('Generated human speech delegated to the native Codex agent and created the requested file.');
 }catch(e){console.error(e.message);if(win)fs.writeFileSync(out+'/failure.json',await win.webContents.executeJavaScript('JSON.stringify({history:window.gla_live?.conversation(),events:window.qaEvents,error:window.qaError})').catch(()=>'{}'));process.exitCode=1;}finally{if(win)await win.webContents.executeJavaScript('gla_live?.stop();window.qaSilence?.stop();window.qaClock?.close();').catch(()=>{});fs.rmSync(app.getPath('userData')+'/openai-key.bin',{force:true});app.exit(process.exitCode||0);}});
