const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const load=async file=>import('data:text/javascript;base64,'+Buffer.from(fs.readFileSync(path.join(__dirname,'../web',file),'utf8')).toString('base64'));
(async()=>{const {NaturalAttention}=await load('avatar3d-attention.js');let seed=913;const rng=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296),a=new NaturalAttention(rng);const starts=[],targets=new Set();let was=false,maxAngle=0,peak=0;
 for(let now=10;now<180000;now+=10){const s=a.sample(now);assert.equal(s.blink.l,s.blink.r);assert(s.blink.l>=0&&s.blink.l<=1);if(s.blink.l>0&&!was)starts.push(now);was=s.blink.l>0;peak=Math.max(peak,s.blink.l);maxAngle=Math.max(maxAngle,Math.hypot(s.eyeOffset.x,s.eyeOffset.y));targets.add(a.nextLook);}
 const intervals=starts.slice(1).map((n,i)=>n-starts[i]);assert(starts.length>25&&starts.length<80);assert(intervals.some(v=>v<800),'Occasional double blink');assert(new Set(intervals.map(v=>Math.round(v/100))).size>12,'Irregular blink intervals');assert(peak>.99);assert(maxAngle<=.01201&&maxAngle>.007);assert(targets.size>60);assert.deepEqual(a.sample(180001,{reduce:true}),{blink:{l:0,r:0},eyeOffset:{x:0,y:0}});
 const companion=await load('avatar3d-companion.js');Object.assign(globalThis,await load('group-context.js'));const code=fs.readFileSync(path.join(__dirname,'../web/group-actions.js'),'utf8').replace("import {avatarIntent,motionIntent} from '/avatar3d-companion.js';",'const {avatarIntent,motionIntent}=globalThis.glaCompanion;').replace("import {addressedSpeaker,addressedText} from '/group-context.js';",'');globalThis.glaCompanion=companion;const {groupAction}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
 const clips=new Map([['kung-fu-punch',{id:'kung-fu-punch',label:'Kung fu punch'}],['wave',{id:'wave'}]]);const cast=['Tia','Sarah','Ming-Mei','Iselda','Seraphim'].map(name=>({name,slug:name.toLowerCase(),clips}));for(const c of cast)assert.deepEqual(groupAction(c.name+', do a kung fu punch',cast,'tia'),{slug:c.slug,action:'clip:kung-fu-punch'});for(const text of ["Tia, don't do kung fu",'Sarah, explain kung fu','"Tia, do a kung fu punch"'])assert.equal(groupAction(text,cast,'tia'),null);
 console.log('Natural binocular blinks, irregular bounded saccades, reduced motion and named group actions passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
