'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),vm=require('node:vm');
const {DelegateAuth,tokenRecord}=require('../electron/delegate-auth.cjs');
const {DelegateBackend,normalizeDelegate,selected,usesCodexServer,usesCodexActions,codexConfig,streamText}=require('../electron/delegate.cjs');
const output=path.resolve(__dirname,'../build/qa-delegate');fs.mkdirSync(output,{recursive:true});
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});
const sse=events=>new Response(events.map(e=>'data: '+(typeof e==='string'?e:JSON.stringify(e))+'\n\n').join(''),{headers:{'Content-Type':'text/event-stream'}});
const jwt='header.'+Buffer.from(JSON.stringify({'https://api.openai.com/auth':{chatgpt_account_id:'test-account'}})).toString('base64url')+'.signature';
const token={access_token:jwt,refresh_token:'test-refresh',expires_in:864000};
const checks=[];
(async()=>{
 let config=normalizeDelegate({});assert.equal(selected(config).model,'gpt-5.6-luna');
 config={...config,...normalizeDelegate(config,{delegateAuth:'oauth2'})};assert.equal(selected(config).model,'gpt-5.6-sol');
 config={...config,...normalizeDelegate(config,{delegateModel:'gpt-5.6-terra'})};
 config={...config,...normalizeDelegate(config,{delegateProvider:'xai'})};assert.equal(selected(config).model,'grok-4.6');
 config={...config,...normalizeDelegate(config,{delegateProvider:'openai'})};assert.equal(selected(config).model,'gpt-5.6-terra');
 assert.equal(selected(normalizeDelegate({delegateProvider:'bad',delegateAuth:'bad'})).model,'gpt-5.6-luna');
 const enconvo=normalizeDelegate(config,{delegateProvider:'enconvo',delegateAuth:'api_key'});assert.equal(selected(enconvo).auth,'local_runtime','EnConvo is always an existing local connection');assert.equal(selected(enconvo).model,'','and keeps each agent\'s own model');
 checks.push('Defaults, validation and independent model persistence');
 { // A spoken answer never aborts a long document (an Avatar Show script) for the same owner, and vice versa.
  const slow=new DelegateBackend({auth:{bearer:async()=>({access:'t'})},fetchImpl:(url,init)=>new Promise((resolve,reject)=>{init.signal.addEventListener('abort',()=>reject(Object.assign(Error('aborted'),{name:'AbortError'})));})});
  const cfg=normalizeDelegate({},{reasoningMode:'delegate'});
  const script=slow.answer(7,'script-1',cfg,[{role:'user',text:'write'}],'',{long:true});script.catch(()=>{});
  const spoken=slow.answer(7,'spoken-1',cfg,[{role:'user',text:'hi'}],'');spoken.catch(()=>{});
  await new Promise(r=>setTimeout(r,20));assert.equal(slow.requests.size,2,'both in flight');
  slow.cancel(7,undefined,{long:false});await new Promise(r=>setTimeout(r,10));assert.equal([...slow.requests.values()].map(r=>r.id).join(),'script-1','only the spoken class was cancelled');
  slow.cancel(7,undefined,{long:true});await new Promise(r=>setTimeout(r,10));assert.equal(slow.requests.size,0);
  checks.push('Cancellation by request class: a Director answer leaves the Playwright alone');
 }
 const server=normalizeDelegate(config,{reasoningMode:'delegate',delegateAuth:'codex_app_server',delegateModel:'gpt-6-astra'});
 assert(usesCodexServer(server));assert(usesCodexActions({...server,agentEngine:'basic'}));assert.equal(codexConfig({...server,agentCodexModel:'legacy'}).agentCodexModel,'gpt-6-astra');
 assert.equal(selected(normalizeDelegate(server,{delegateAuth:'oauth2'})).model,'gpt-5.6-terra');
 assert.equal(selected(normalizeDelegate(server,{delegateProvider:'xai'})).auth,'api_key');
 assert.equal(selected(normalizeDelegate(server,{delegateModel:''})).model,'');
 const routed=[],serverBackend=new DelegateBackend({auth:{bearer:()=>{throw Error('Must not use direct credentials');}},fetchImpl:()=>{throw Error('Must not make API calls');},codex:{answer:async(...args)=>{routed.push(args);return {text:'Codex answer',model:args[2].agentCodexModel};},status:async()=>({models:['gpt-6-astra']}),cancel:()=>{},cancelAll:()=>{}}});
 assert.equal((await serverBackend.answer(1,'codex',server,[{role:'user',text:'A question'}],'Reasoning')).model,'gpt-6-astra');assert.equal(routed.length,1);assert.deepEqual(await serverBackend.models(server),['gpt-6-astra']);
 await assert.rejects(new DelegateBackend({auth:{}}).answer(1,'missing',server,[{role:'user',text:'Question'}],''),/not connected/);
 checks.push('Codex App Server routing without direct credentials or API fallback, model persistence and provider isolation');
 const directory=path.join(output,'credentials');fs.rmSync(directory,{recursive:true,force:true});
 // Fake encryption is confined to this test, with a fresh throwaway profile.
 const storage={isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from(Buffer.from(s).toString('base64')),decryptString:b=>Buffer.from(b.toString(),'base64').toString()};
 let opened=[],posts=[],authFetch=async(url,opts)=>{posts.push({url,form:Object.fromEntries(opts.body)});return json(token);};
 const auth=new DelegateAuth({directory,safeStorage:storage,readOpenAIKey:()=> 'test-api-key',openExternal:async url=>{opened.push(url);},fetchImpl:(...args)=>authFetch(...args),callbackPort:15455});
 await auth.start('openai');const login=new URL(opened.pop()),state=login.searchParams.get('state');
 assert.equal(login.origin,'https://auth.openai.com');assert.equal(login.searchParams.get('code_challenge_method'),'S256');
 let r=await fetch('http://127.0.0.1:15455/auth/callback?state=wrong&code=not-used');assert.equal(r.status,400);assert.equal(posts.length,0);
 r=await fetch('http://127.0.0.1:15455/auth/callback?'+new URLSearchParams({state,code:'test-code'}));assert.equal(r.status,200);await r.text();
 assert(auth.status().openai.signedIn);assert(auth.read('openai').expires>Date.now()+9*86400000);const exchange=posts[0].form;
 assert.equal(crypto.createHash('sha256').update(exchange.code_verifier).digest('base64url'),login.searchParams.get('code_challenge'));
 assert.equal(exchange.redirect_uri,'http://localhost:15455/auth/callback');assert(!JSON.stringify(auth.status()).includes(jwt));assert(!fs.readFileSync(auth.file('openai')).includes('test-refresh'));
 checks.push('OpenAI PKCE callback, wrong-state rejection and credential isolation');
 auth.write('openai',{access:jwt,refresh:'test-refresh',expires:0});posts=[];
 authFetch=async(url,opts)=>{posts.push({url,form:Object.fromEntries(opts.body)});await wait(30);return json({access_token:jwt,expires_in:3600});};
 await Promise.all([auth.bearer('openai','oauth2'),auth.bearer('openai','oauth2')]);assert.equal(posts.length,1);assert.equal(auth.read('openai').refresh,'test-refresh');
 auth.write('openai',{access:jwt,refresh:'test-refresh',expires:0});const refresh=auth.bearer('openai','oauth2');auth.signOut('openai');await assert.rejects(refresh,/Sign-in changed/);assert(!auth.status().openai.signedIn);
 assert.throws(()=>tokenRecord({access_token:'x',refresh_token:'y'}));checks.push('Single refresh, rotated-token preservation, sign-out race and missing expiry');
 for(const expiry of [0,-1,Infinity,1e30,null,true,'bad'])assert.throws(()=>tokenRecord({...token,expires_in:expiry}),/expiry/);
 assert(tokenRecord({...token,expires_in:'864000'}).expires>Date.now()+9*86400000);
 authFetch=async()=>json({error:'invalid_grant',error_description:'secret-provider-detail'},400);
 await auth.start('openai');const failedLogin=new URL(opened.pop());
 const failed=await fetch('http://127.0.0.1:15455/auth/callback?'+new URLSearchParams({state:failedLogin.searchParams.get('state'),code:'expired-code'}));
 const failureText=await failed.text();assert.equal(failed.status,400);assert.match(failureText,/expired or was already used/);assert(!failureText.includes('secret'));assert.match(auth.status().openai.error,/HTTP 400/);
 checks.push('Provider lifetime beyond seven days, invalid lifetime rejection and actionable callback errors');
 let polls=0;authFetch=async url=>url.endsWith('/device/code')?json({device_code:'secret-device',user_code:'ABCD-EFGH',verification_uri:'https://auth.x.ai/activate',expires_in:60,interval:1}):(++polls===1?json({error:'authorization_pending'},400):json(token));
 await auth.start('xai');assert.equal(auth.status().xai.userCode,'ABCD-EFGH');assert(!JSON.stringify(auth.status()).includes('secret-device'));await wait(2200);assert(auth.status().xai.signedIn);
 auth.signOut('xai');authFetch=async()=>json({device_code:'secret',user_code:'TEST',verification_uri:'https://evil.example/activate',expires_in:60});await auth.start('xai');assert.equal(auth.status().xai.state,'error');assert(!auth.pending.has('xai'));
 let release;authFetch=()=>new Promise(r=>release=r);const pending=auth.start('xai');auth.cancel('xai');release(json({device_code:'secret',user_code:'TEST',verification_uri:'https://auth.x.ai/activate',expires_in:60}));await pending;assert(!auth.pending.has('xai'));assert(!auth.status().xai.signedIn);
 checks.push('xAI device polling, private device code, host validation and cancelled-start race');
 const routes=[];const backend=new DelegateBackend({auth:{bearer:async(p,a)=>({access:a==='oauth2'?jwt:'api-key'})},fetchImpl:async(url,opts)=>{routes.push({url,headers:opts.headers,body:JSON.parse(opts.body)});return url.includes('chat/completions')?sse([{choices:[{delta:{content:'It works.'},finish_reason:'stop'}]},'[DONE]']):sse([{type:'response.output_text.delta',delta:'It works.'},{type:'response.completed'}]);}});
 for(const provider of ['openai','xai'])for(const authMode of ['api_key','oauth2']){const c=normalizeDelegate({},{delegateProvider:provider,delegateAuth:authMode});const result=await backend.answer(1,'test',c,[{role:'user',text:'Question?'}],'Helpful');assert.equal(result.text,'It works.');}
 assert.equal(routes[0].url,'https://api.openai.com/v1/responses');assert.equal(routes[0].body.model,'gpt-5.6-luna');
 assert.equal(routes[1].url,'https://chatgpt.com/backend-api/codex/responses');assert.equal(routes[1].body.model,'gpt-5.6-sol');assert.equal(routes[1].headers['chatgpt-account-id'],'test-account');assert(!Object.hasOwn(routes[1].body,'max_output_tokens'));assert.equal(routes[1].body.store,false);
 assert.equal(routes[2].url,'https://api.x.ai/v1/chat/completions');assert.equal(routes[3].url,'https://cli-chat-proxy.grok.com/v1/chat/completions');assert.equal(routes[3].body.model,'grok-build');assert.equal(routes[3].headers['x-grok-model-override'],'grok-4.6');
 await assert.rejects(streamText(sse([{type:'response.output_text.delta',delta:'Partial'}])),/ended before/);
 await assert.rejects(streamText(sse([{type:'response.failed',error:{message:'secret-provider-body'}}])),/could not finish/);
 backend.fetch=async()=>json({error:{message:'secret-token'}},401);await assert.rejects(backend.answer(1,'bad',{},[{role:'user',text:'Q'}],''),e=>!e.message.includes('secret')&&/Authentication/.test(e.message));
 const frames=Buffer.from('data: '+JSON.stringify({type:'response.output_text.delta',delta:'你好'})+'\r\n\r\ndata: '+JSON.stringify({type:'response.completed'})+'\r\n\r\n');
 assert.equal(await streamText(new Response(new ReadableStream({start(controller){for(const byte of frames)controller.enqueue(Uint8Array.of(byte));controller.close();}}))),'你好');
 backend.fetch=async()=>json({data:[{id:'gpt-6-astra'},{id:'gpt-5.6-terra'},{id:'gpt-5.6-luna'},{id:'gpt-5.6-sol'},{id:'gpt-image-2'}]});
 const apiModels=await backend.models(normalizeDelegate({})),oauthModels=await backend.models(normalizeDelegate({delegateAuth:'oauth2'}));
 for(const model of ['gpt-6-astra','gpt-5.6-sol','gpt-5.6-terra','gpt-5.6-luna']){assert(apiModels.includes(model));assert(oauthModels.includes(model));}assert(!apiModels.includes('gpt-image-2'));
 checks.push('Four authenticated inference routes, Astra/Terra/Luna/Sol catalogue, correct wire formats and safe stream errors');
 const context=vm.createContext({EventTarget,Event,CustomEvent,performance,setTimeout,clearTimeout,TextEncoder});
 vm.runInContext(fs.readFileSync(path.resolve(__dirname,'../web/delegate-client.js'),'utf8').replace(/export /g,'')+'\nglobalThis.Bridge=DelegateClient;globalThis.chunks=commentaryChunks;',context);
 class Live extends EventTarget{constructor(){super();this.reasoningMode='delegate';this.generation=1;this.state='connected';this.sent=[];}conversation(){return [{role:'user',text:'Unfinished question segment'}];}appendCommentary(content,id){this.sent.push({content,id});return true;}emit(type,detail){this.dispatchEvent(new CustomEvent(type,{detail}));}}
 const live=new Live(),requests=[];let finish;
 const bridge=new context.Bridge(live,{answer:async req=>{requests.push(req);return new Promise(r=>finish=r);},cancel:async()=>{}});
 live.emit('event',{type:'session.delegation.created',delegation:{target:'client',id:'delegate-1'}});live.emit('event',{type:'session.delegation.created',delegation:{target:'client',id:'delegate-1'}});await wait(420);assert.equal(requests.length,1);assert.equal(requests[0].history[0].text,'Unfinished question segment');finish({ok:true,text:'Answer.'});await wait(10);assert.equal(live.sent[0].id,'delegate-1');
 live.emit('transcript',{role:'user',id:'turn-1'});live.emit('event',{type:'session.delegation.created',delegation:{target:'client',id:'delegate-2'}});await wait(500);live.emit('transcript',{role:'user',id:'turn-2'});finish({ok:true,text:'Stale.'});await wait(10);assert.equal(live.sent.length,1);
 live.emit('state',{state:'idle'});const chinese='你好🙂'.repeat(700);const chunks=context.chunks(chinese);assert.equal(chunks.join(''),chinese);assert(chunks.every(s=>Buffer.byteLength(s)<=400));
 auth.close();checks.push('Real delegation ID, unfinished transcript, duplicate suppression, interrupted answers and multilingual append limits');
 fs.writeFileSync(path.join(output,'results.json'),JSON.stringify({checks},null,2));console.log(checks.join('\n'));
})().catch(error=>{console.error(error);process.exit(1);});
