// Real desktop group UI with deterministic reasoning/audio substitutes.
// Exercises human turn scheduling and actual renderer facing without opening a mic.
const {app,BrowserWindow,ipcMain,safeStorage}=require('electron'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
const repo=path.resolve(__dirname,'..'),out=path.join(repo,'build/qa-group-human');fs.mkdirSync(out,{recursive:true});app.setPath('userData',out+'/profile');fs.mkdirSync(app.getPath('userData'),{recursive:true});delete process.env.GLA_OPENAI_KEY;
fs.writeFileSync(app.getPath('userData')+'/config.json',JSON.stringify({avatar:'tia',quality:'balanced'}));fs.mkdirSync(app.getPath('userData')+'/avatars',{recursive:true});for(const slug of ['tia','sarah','iselda','ming-mei','seraphim']){const link=app.getPath('userData')+'/avatars/'+slug;if(!fs.existsSync(link))fs.symlinkSync(repo+'/build/characters/'+slug,link);}
app.whenReady().then(()=>fs.writeFileSync(app.getPath('userData')+'/openai-key.bin',safeStorage.encryptString('sk-local-qa-placeholder')));
const replies=[],errors=[];require('../electron/delegate.cjs').DelegateBackend.prototype.answer=async(owner,id,config,history,instructions)=>{replies.push({history,instructions});return {text:history[0].text.includes('tiny dragon')?'A tiny dragon joins our adventure, and we follow it to the floating city.':'A mysterious invitation arrives. Shall we explore the floating city together?'};};
let uploads=0;require('../electron/group-input.cjs').transcribe=async()=>{uploads++;return {text:'I choose a tiny dragon.'};};
app.on('browser-window-created',(_e,w)=>w.webContents.on('console-message',d=>{if(d.level==='error')errors.push(d.message);}));require('../electron/main.cjs');
const wait=ms=>new Promise(r=>setTimeout(r,ms));async function until(fn,label){const end=Date.now()+120000;while(Date.now()<end){try{const value=await fn();if(value)return value;}catch{}await wait(80);}throw Error('Timeout '+label);}
app.whenReady().then(async()=>{try{
 const primary=await until(()=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/avatar.html')),'primary');await until(()=>primary.webContents.executeJavaScript('Boolean(window.gla_avatar?.model)'),'primary ready');await primary.webContents.executeJavaScript('gla.group.open()');const win=await until(()=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/group.html')),'group'),js=s=>win.webContents.executeJavaScript('(async()=>{'+s+'})()');await until(()=>js('return window.gla_group&&!gla_group.state.loading&&gla_group.actors.size===2'),'loaded');
 await js(`document.querySelector('#liveMode').checked=false;document.querySelector('#join').checked=false;window.spoken=[];window.voiceDelay=120;gla_group.voice.speak=async(text,voice,onText)=>{window.spoken.push(text);onText(text);await new Promise(r=>setTimeout(r,window.voiceDelay));return text;};document.querySelector('#join').click();document.querySelector('#humanName').value='Jamie';document.querySelector('#format').value='story';document.querySelector('#format').dispatchEvent(new Event('change'));document.querySelector('#rounds').value='4';`);
 fs.writeFileSync(out+'/controls.png',(await win.webContents.capturePage()).toPNG());
 await js('void gla_group.start();');await until(()=>js('return gla_group.state.waitingHuman'),'your turn');const count=replies.length;assert.equal(count,2);await wait(1200);assert.equal(replies.length,count,'No auto-generated human answer');const state=await js('return gla_group.state');assert.equal(state.speaker,'_human');assert.equal(state.history.length,2);assert(await js('return [...gla_group.actors.values()].every(a=>Math.abs(a.yaw)<.06)'),'Faces audience while human speaks');
 fs.writeFileSync(out+'/your-turn.png',(await win.webContents.capturePage()).toPNG());
 // A generated audio stream tests the real recorder path, without mic capture.
 await js(`window.fakeCaptures=0;navigator.mediaDevices.getUserMedia=async()=>{window.fakeCaptures++;const c=new AudioContext(),d=c.createMediaStreamDestination(),s=c.createOscillator();s.connect(d);s.start();window.testStream=d.stream;window.testAudio=c;return d.stream;};document.querySelector('#mic').click();`);await until(()=>js("return gla_group.microphone.state==='recording'"),'recording');await wait(450);await js("document.querySelector('#mic').click();");await until(()=>js("return gla_group.microphone.state==='idle'&&document.querySelector('#humanText').value.includes('tiny dragon')"),'draft');assert.equal(uploads,1);assert.equal(replies.length,count,'Transcription waits for explicit Send');assert(await js("return testStream.getTracks().every(t=>t.readyState==='ended')"),'Microphone released before draft review');
 await js("document.querySelector('#send').click();");await until(()=>js('return !gla_group.state.running'),'finished');assert.equal(replies.length,4);assert(replies[2].history[0].text.includes('Jamie (real human): I choose a tiny dragon.'));assert(replies[3].instructions.includes('final character turn'));fs.writeFileSync(out+'/human-story.png',(await win.webContents.capturePage()).toPNG());
 // Request the next turn early, then stop while paused and reject late input.
 await js('window.voiceDelay=800;void gla_group.start();');await until(()=>js('return gla_group.state.running&&window.spoken.length===5'),'first speaker');await js("document.querySelector('#raise').click();");await until(()=>js('return gla_group.state.waitingHuman'),'early hand');assert.equal(replies.length,5);await js('gla_group.stop();');const stopped=replies.length;await js("document.querySelector('#humanText').value='Must not send';document.querySelector('#send').click();");await wait(150);assert.equal(replies.length,stopped);assert(await js("return document.querySelector('#humanTurn').hidden&&gla_group.microphone.state==='idle'"));
 // Passing is an actual choice, not an invented line from the human.
 await js('window.voiceDelay=80;void gla_group.start();');await until(()=>js('return gla_group.state.waitingHuman'),'pass pause');await js("document.querySelector('#pass').click();");await until(()=>js('return !gla_group.state.running'),'pass finish');assert(!(await js('return gla_group.state.history')).some(x=>x.speaker==='_human'));
 // Audience-only mode still runs without a human pause or capture.
 await js("document.querySelector('#join').click();void gla_group.start();");await until(()=>js('return !gla_group.state.running'),'spectator finish');assert.equal(await js('return window.fakeCaptures'),1);
 // Only the actual group window may submit recordings.
 const denied=await primary.webContents.executeJavaScript("gla.group.transcribe({audio:new Uint8Array(256),mime:'audio/webm'})");assert.equal(denied.ok,false);assert.equal(uploads,1);
 await js("document.querySelector('#join').checked=true;void gla_group.start();");await until(()=>js('return gla_group.state.waitingHuman'),'hidden pause');await js("document.querySelector('#mic').click();");await until(()=>js("return gla_group.microphone.state==='recording'"),'hidden mic');win.hide();await until(()=>js("return gla_group.microphone.state==='idle'&&testStream.getTracks().every(t=>t.readyState==='ended')"),'hidden mic release');await until(()=>js('return !gla_group.state.running'),'15-second hidden stop');win.show();assert.equal(uploads,1,'Hidden recording not uploaded');
 await js('await testAudio.close();await gla.group.close();');await wait(300);assert(primary.isVisible());assert.deepEqual(errors,[]);fs.writeFileSync(out+'/report.json',JSON.stringify({passed:true,checks:['human wait','audience eye contact','no invented human turns','voice draft review','microphone tracks released','human reply in next model context','early requested turn','stop and late-send isolation','pass','spectator mode','recording IPC isolation','hidden microphone immediately released','hidden group auto-stop','close restores primary'],replies:replies.length,uploads,errors},null,2));console.log('Human group native UI checks passed.');
 }catch(e){console.error(e);console.error(errors);process.exitCode=1;}finally{app.exit(process.exitCode||0);}});
