const {app,BrowserWindow}=require('electron'),fs=require('fs'),path=require('path'),http=require('http'),zlib=require('zlib'),assert=require('assert/strict');
// Isolated asset-backed regression: no microphone, API calls, or installed app settings.
// Requires prepared Ming-Mei assets, including the corrected motion pelvis/spine bake.
const repo=path.resolve(process.env.GLA_QA_REPO||path.join(__dirname,'..'));
const out=path.resolve(process.env.GLA_QA_OUTPUT||path.join(repo,'build/qa-mingmei-dress'));
const candidate=process.env.GLA_QA_MOTIONS?path.resolve(process.env.GLA_QA_MOTIONS):null;
const overlay=process.env.GLA_QA_OVERLAY?path.resolve(process.env.GLA_QA_OVERLAY):null;fs.mkdirSync(out,{recursive:true});app.setPath('userData',out+'/profile');app.on('window-all-closed',()=>{});
let mode='before';const errors=[];
const server=http.createServer((req,res)=>{const u=decodeURIComponent(req.url.split('?')[0]);if(u==='/'){res.setHeader('Content-Type','text/html');return res.end('<script type="module" src="/avatar3d.js"></script>');}let file=u.startsWith('/asset/')?repo+'/build/characters/'+u.slice(7):candidate&&u.startsWith('/candidate/')?candidate+'/'+u.slice(11):overlay&&['/avatar3d-garment-fit.js','/avatar3d-mingmei-fit.js'].includes(u)?overlay+u:repo+'/web'+u;if(!fs.existsSync(file)&&fs.existsSync(file+'.deflate')){res.setHeader('Content-Type','application/json');return res.end(zlib.inflateRawSync(fs.readFileSync(file+'.deflate')));}if(!fs.existsSync(file)){res.statusCode=404;return res.end(file);}res.setHeader('Content-Type',({'.js':'text/javascript','.json':'application/json','.gltf':'model/gltf+json'})[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);});
app.whenReady().then(async()=>{try{await new Promise(r=>server.listen(0,'127.0.0.1',r));const report=[];
for(mode of ['after']){const w=new BrowserWindow({show:false,width:850,height:1000,webPreferences:{backgroundThrottling:false}});w.webContents.on('console-message',d=>{if(d.level==='error')errors.push(d.message);});await w.loadURL('http://127.0.0.1:'+server.address().port+'/?'+mode);
const result=await w.webContents.executeJavaScript(`(async()=>{while(!window.OpenClamAvatar3D)await new Promise(r=>setTimeout(r,20));const T=await import('/vendor/three/three.module.js');window.shots=[];const a=OpenClamAvatar3D.create({width:640,height:950});await a.load('/asset/ming-mei/runtime/resident/model.gltf',{resources:true,performance:'balanced',appearanceLibrary:'/asset/ming-mei/appearance/index.json',motionLibrary:'/asset/ming-mei/runtime/motions/library.json'});a.options.select({outfit:'dress',prop:'none',hands:'none',leftHand:'none',rightHand:'none',performance:'balanced',lighting:'studio',playTransitions:'false',body:'Ps007.stand'});a.options.playback=[];await a.resources.update('balanced',1200,true);
const garment=[...a.resources.meshes.values()].flatMap(r=>r.nodes).find(n=>(n.userData.sourceName||n.name)==='Dress01');let dress; a.model.traverse(n=>{if((n.userData.sourceName||n.name)==='Dress01')dress=n;});const fitted=dress.geometry.userData.avatarMingMeiFit||null;let body;a.model.traverse(n=>{if((n.userData.sourceName||n.name)==='Body')body=n;});const m=body.material,hook=m.onBeforeCompile,key=m.customProgramCacheKey;m.onBeforeCompile=(shader,r)=>{hook.call(m,shader,r);shader.uniforms.qaBack={value:false};window.qaBack=shader.uniforms.qaBack;shader.vertexShader='varying vec3 qaRest;\\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\\nqaRest=position;');shader.fragmentShader='varying vec3 qaRest;uniform bool qaBack;\\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <dithering_fragment>','#include <dithering_fragment>\\nif(qaBack&&qaRest.y>.91&&qaRest.y<1.085&&abs(qaRest.x)<.105&&qaRest.z<.015)gl_FragColor=vec4(1.,0.,1.,1.);');};m.customProgramCacheKey=()=>key.call(m)+'-qa-back';m.needsUpdate=true;const coverage=[];
const hash=node=>{let h=2166136261;for(const name of ['position','skinIndex','skinWeight']){const a=node.geometry.attributes[name].array;const bytes=new Uint8Array(a.buffer,a.byteOffset,a.byteLength);for(const b of bytes)h=Math.imul(h^b,16777619);}return h>>>0;};
const firstGeometry=dress.geometry,firstHash=hash(dress),bodyHash=hash(body);const fitting=await import('/avatar3d-mingmei-fit.js');fitting.fitMingMeiDress(dress);const idempotent=firstHash===hash(dress);
a.options.select({outfit:'workout',performance:'eco'});a.options.playback=[];await a.resources.update('eco',300,true);const evicted=dress.geometry.attributes.position.count===0;
a.options.select({outfit:'dress',performance:'eco'});a.options.playback=[];await a.resources.update('eco',300,true);
const reloaded=dress.geometry!==firstGeometry&&!!dress.geometry.userData.avatarMingMeiFit,reapplied=firstHash===hash(dress);
await a.resources.update('quality',1200,true);await a.resources.update('eco',300,true);a.options.select({performance:'balanced'});a.options.playback=[];await a.resources.update('balanced',1200,true);
const reload={idempotent,evicted,reloaded,reapplied,tierStable:firstHash===hash(dress),bodyUnchanged:bodyHash===hash(body)};
const take=(name,now)=>{const state={bodyMotion:false,fitContent:true,stableFitContent:true,reduce:false};a.render(now,state);const v=a.currentView,part={x:v.x+v.w*.19,y:v.y+v.h*.24,w:v.w*.62,h:v.h*.66,pixelWidth:750,pixelHeight:1000};a.render(now,state,part);shots.push({name,data:a.canvas.toDataURL()});qaBack.value=true;a.renderer.render(a.scene,a.camera);const pixels=new Uint8Array(a.canvas.width*a.canvas.height*4);a.renderer.getContext().readPixels(0,0,a.canvas.width,a.canvas.height,6408,5121,pixels);let exposed=0;for(let i=0;i<pixels.length;i+=4)if(pixels[i]>240&&pixels[i+1]<10&&pixels[i+2]>240&&pixels[i+3]>240)exposed++;coverage.push({name,exposed});qaBack.value=false;};
for(const id of ['happy-jump-female','bubble-dance']){if(${Boolean(candidate)})a.motion.clips.get(id).url=location.origin+'/candidate/ming-mei/'+id+'.json';const clip=await a.motion.prepare(id),duration=(clip.frames.length-1)/clip.fps;
for(const yaw of [0,Math.PI/2,Math.PI,Math.PI*1.5]){a.setOrbit({yaw,pitch:0});await a.motion.play(id,{now:1000,loop:false});a.motion.active.start=-1000;
for(const phase of [1.1/8,3.1/8,5.1/8,7.1/8]){const now=1000+duration*phase*1000;a.render(now,{bodyMotion:false,fitContent:true,stableFitContent:true});await a.resources.update('balanced',1200,true);take(id+'-'+Math.round(yaw*180/Math.PI)+'-'+Math.round(phase*100),now);}}}
const weights=dress.geometry.attributes.skinWeight;let error=0;for(let i=0;i<weights.count;i++)error=Math.max(error,Math.abs(weights.getX(i)+weights.getY(i)+weights.getZ(i)+weights.getW(i)-1));const gl=a.renderer.getContext().getError();a.dispose();return {fitted,weightError:error,gl,coverage,reload};})()`);
for(const shot of await w.webContents.executeJavaScript('shots'))fs.writeFileSync(out+'/'+mode+'-'+shot.name+'.png',Buffer.from(shot.data.split(',')[1],'base64'));
assert.equal(result.gl,0);assert(result.weightError<1e-5);assert(result.fitted?.vertices>100);assert(Object.values(result.reload).every(Boolean),'Garment streaming regression: '+JSON.stringify(result.reload));assert.equal(result.coverage.length,32);assert(result.coverage.every(v=>v.exposed===0),'Opaque dress back exposed: '+JSON.stringify(result.coverage.filter(v=>v.exposed)));assert(result.fitted.maximumEase<=.0091);report.push({mode,...result});w.destroy();}
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/report.json',JSON.stringify({passed:true,report,errors},null,2));console.log(JSON.stringify(report));
}catch(e){console.error(e,errors);process.exitCode=1;}finally{server.close();app.exit(process.exitCode||0);}});
