// Requires licensed local build/characters packages; never uploads source models.
const {app,BrowserWindow}=require('electron'),fs=require('fs'),path=require('path'),http=require('http'),zlib=require('zlib');
const root=path.resolve(__dirname,'..'),out=root+'/build/qa-motions';fs.mkdirSync(out,{recursive:true});app.setPath('userData',out+'/profile');app.on('window-all-closed',()=>{});
const server=http.createServer((req,res)=>{const u=decodeURIComponent(req.url.split('?')[0]);if(u==='/'){res.setHeader('Content-Type','text/html');return res.end('<script type="module" src="/avatar3d.js"></script>');}const file=u.startsWith('/asset/')?root+'/build/characters/'+u.slice(7):u.startsWith('/audit/')?out+'/'+u.slice(7):root+'/web'+u;if(!fs.existsSync(file)&&fs.existsSync(file+'.deflate')){res.setHeader('Content-Type','application/json');return res.end(zlib.inflateRawSync(fs.readFileSync(file+'.deflate')));}if(!fs.existsSync(file)){res.statusCode=404;return res.end();}res.setHeader('Content-Type',({'.js':'text/javascript','.json':'application/json','.gltf':'model/gltf+json'})[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);});
app.whenReady().then(async()=>{try{await new Promise(r=>server.listen(0,'127.0.0.1',r));const w=new BrowserWindow({show:false,width:1200,height:1000,webPreferences:{backgroundThrottling:false}});await w.loadURL('http://127.0.0.1:'+server.address().port);const result=await w.webContents.executeJavaScript(`(async()=>{
 while(!window.OpenClamAvatar3D)await new Promise(r=>setTimeout(r,20));const T=await import('/vendor/three/three.module.js');
window.shots=[];const result={};
for(const slug of ['tia','sarah','iselda','ming-mei','seraphim']){const a=OpenClamAvatar3D.create({width:440,height:640});await a.load('/asset/'+slug+'/runtime/resident/model.gltf',{resources:true,pose:'rest',performance:'eco',appearanceLibrary:'/asset/'+slug+'/appearance/index.json',motionLibrary:'/asset/'+slug+'/runtime/motions/library.json'});await a.resources.update('eco',1200,true);
 a.options.select({prop:'none',hands:'none',leftHand:'none',rightHand:'none',performance:'eco',playTransitions:'false',body:'Ps007.stand'});a.options.playback=[];a.setOrbit({yaw:0,pitch:0});
 for(const id of ['bubble-dance','boxing-warm-up','backflip','360-power-spin-jump','all-night-dance']){
 let data;try{data=await a.motion.prepare(id);}catch(e){const raw=await(await fetch('/asset/'+slug+'/runtime/motions/'+id+'.json')).json();throw Error(slug+' '+id+': '+e.message+' bones '+a.options.bones.length+'/'+raw.bones.length+' frame '+raw.frames[0].length+' id '+raw.id);}const duration=(data.frames.length-1)/data.fps;result[slug+'-'+id]={frames:data.frames.length,fps:data.fps};
 await a.motion.play(id,{now:1000,loop:false});a.motion.active.start=-1000;if(a.motion.active.hands.some(Boolean))throw Error('No-prop incorrectly preserves fingers: '+slug);if(id==='boxing-warm-up'&&!a.motion.active.authoredHands.some(Boolean))throw Error('Missing authored fists: '+slug);
 for(let i=0;i<8;i++){const now=1000+duration*(i+.1)/8*1000;a.render(now,{cameraFocus:false,audienceContact:false,fitContent:true,stableFitContent:true,bodyMotion:false});await a.resources.update('eco',1200,true);a.render(now,{cameraFocus:false,audienceContact:false,fitContent:true,stableFitContent:true,bodyMotion:false});const view=a.currentView;if(view.h>640*5||view.w>440*5)throw Error('Motion inherited an oversized viewport: '+slug+' '+id);window.shots.push({name:slug+'-'+id+'-'+i,data:a.canvas.toDataURL()});}
 }
 a.dispose();}
return result;})()`);fs.writeFileSync(out+'/all-five-info.json',JSON.stringify(result));for(const shot of await w.webContents.executeJavaScript('shots'))fs.writeFileSync(out+'/'+shot.name+'.png',Buffer.from(shot.data.split(',')[1],'base64'));console.log('All five characters: 25 clips, 200 rendered phases, native fists and bounded framing passed.');}catch(e){console.error(e);process.exitCode=1;}finally{server.close();app.exit(process.exitCode||0);}});
