const {app,BrowserWindow,Menu,globalShortcut}=require('electron');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const output=path.resolve(__dirname,'../build/qa-placement');fs.mkdirSync(output,{recursive:true});
app.setPath('userData',path.join(output,'profile'));fs.mkdirSync(app.getPath('userData'),{recursive:true});
fs.writeFileSync(path.join(app.getPath('userData'),'config.json'),JSON.stringify({avatar:'tia',quality:'friendly',bubbleMode:'off',windowWidth:500,windowHeight:800,avatarLooks:{tia:{body:'',prop:''}}}));
const errors=[],checks=[];app.on('browser-window-created',(_e,w)=>w.webContents.on('console-message',d=>{if(d.level==='error')errors.push(d.message);}));
require('../electron/main.cjs');
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,label){const end=Date.now()+90000;while(Date.now()<end){try{const result=await fn();if(result)return result;}catch{}await wait(80);}throw Error('Timed out: '+label);}
app.whenReady().then(async()=>{try{
 const w=await until(()=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/avatar.html')),'window');
 const js=s=>w.webContents.executeJavaScript('(async()=>{'+s+'})()');
 await until(()=>js('return !!window.gla_avatar?.model&&gla_avatar.motion?.clips.size>=62&&gla_avatar.resources.ready;'),'ready');
 for(const other of BrowserWindow.getAllWindows())if(other!==w)other.close();
 const choose=id=>w.webContents.send('gla:menu-action',id);
 const capture=async name=>fs.writeFileSync(path.join(output,name+'.png'),(await w.webContents.capturePage()).toPNG());
 await js("await gla_play('closer');");await wait(700);
 await js("await gla_play('go-center');");await wait(600);
 assert(await js('return !!gla_stage()?.studio;'),'Sequence reaches studio placement');
 const initial=await js('return gla_geometry().fit.scale;');
 await js("window.dispatchEvent(new WheelEvent('wheel',{ctrlKey:true,deltaY:-30,cancelable:true}));");await wait(220);
 assert.equal(await js('return !!gla_stage().studio;'),false,'Pinch takes ownership from walking');
 const larger=await js('return gla_geometry().fit.scale;');assert(larger>initial*1.12,'Pinch changes displayed scale after center command');
 await js("window.dispatchEvent(new WheelEvent('wheel',{ctrlKey:true,deltaY:30,cancelable:true}));");await wait(220);
 assert(Math.abs(await js('return gla_geometry().fit.scale;')/initial-1)<.03,'Reverse pinch returns to prior size');
 checks.push('Close-up → center → pinch enlarges and shrinks the displayed avatar');
 await js("await gla_play('closer');");await wait(400);await js("await gla_play('go-center');");await wait(400);
 const hit=await js("const c=document.querySelector('#stage'),d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;for(let y=10;y<c.height-10;y+=4)for(let x=10;x<c.width-10;x+=4)if(d[(y*c.width+x)*4+3]>220)return {x:x/c.width*innerWidth,y:y/c.height*innerHeight};");
 assert(hit,'Avatar painted before drag');
 await js("HTMLCanvasElement.prototype.setPointerCapture=()=>{};");
 const pointer=(type,x,y,buttons)=>js(`document.querySelector('#stage').dispatchEvent(new PointerEvent('${type}',{bubbles:true,pointerId:77,button:0,buttons:${buttons},clientX:${x},clientY:${y},screenX:${x},screenY:${y}}));`);
 await pointer('pointerdown',hit.x,hit.y,1);await wait(250);
 const before=await js('return gla_stage().anchor.x;'),xs=[];
 for(let i=1;i<=12;i++){await pointer('pointermove',hit.x+i*3,hit.y,1);await wait(30);xs.push(await js('return gla_stage().anchor.x;'));}
 await pointer('pointerup',hit.x+36,hit.y,0);
 assert(xs.at(-1)>before+24,'Right drag moves right after studio travel');assert(xs.every((x,i)=>i===0||x>=xs[i-1]-.5),'No reversed samples');
 checks.push('Close-up → center → right drag moves right continuously');
 await js('gla_stage().anchor.x=-1e6;gla_stage().anchor.y=-1e6;');await wait(180);
 const visible=await js('return gla_visibleBox();');assert(visible&&visible.w>20&&visible.h>20,'Manual placement cannot lose the avatar');
 checks.push('Off-screen manual placement is constrained to a reachable head');
 choose('recover');
 const restored=await until(async()=>{const v=await js('return {box:gla_visibleBox(),stage:gla_debug().stage,fit:gla_geometry().fit};');return v.box&&v.box.x>w.getSize()[0]*.75?v:false;},'Recovery restores upper right');await capture('recovery-check');
 const defaults=require('../electron/default-placement.json');assert(Math.abs(await js('return gla_avatar.layout().bounds[3]*gla_stage().scale;')-defaults.bodyHeight)<1,'Recovery restores captured size');
 const first=await js('return JSON.stringify(gla_stage().anchor);');choose('recover');await wait(300);assert.equal(await js('return JSON.stringify(gla_stage().anchor);'),first,'Recovery is repeatable');
 assert(globalShortcut.isRegistered('CommandOrControl+Shift+0'),'Recovery shortcut registered');
 assert(Menu.getApplicationMenu().items.find(i=>i.label==='View').submenu.items.some(i=>i.label==='Bring Avatar Back'),'Menu recovery available');
 const viewMenu=Menu.getApplicationMenu().items.find(i=>i.label==='View').submenu;
 assert.equal(viewMenu.items.find(i=>i.label==='Bring Avatar Back').accelerator,'CommandOrControl+Shift+0');
 assert(globalShortcut.isRegistered('CommandOrControl+Shift+9'));
 assert(!globalShortcut.isRegistered('CommandOrControl+Shift+D'));
 choose('close-up');await wait(1200);
 const close=await js('return {fit:gla_geometry().fit,face:gla_avatar.layout().faceBounds,height:innerHeight,width:innerWidth};');
 assert(close.face[3]*close.fit.scale>close.height*.45,'Face fills the close-up');
 const center={x:close.fit.x+(close.face[0]+close.face[2]/2)*close.fit.scale,y:close.fit.y+(close.face[1]+close.face[3]/2)*close.fit.scale};
 assert(Math.abs(center.x-close.width/2)<close.width*.1,'Face centered');
 await capture('face-closeup');choose('recover');await wait(400);
 assert(Math.abs(await js('return gla_avatar.layout().bounds[3]*gla_stage().scale;')-defaults.bodyHeight)<1,'Normal size restored after close-up');
 checks.push('Face-filling close-up and normal-size return use separate default shortcuts');
 await capture('restored-upper-right');checks.push('⌘⇧0 registered; menu restores captured upper-right size and location repeatedly');
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(output,'report.json'),JSON.stringify({passed:true,checks,restored},null,2));console.log(JSON.stringify({passed:true,checks}));
}catch(e){console.error(e);console.error(errors);process.exitCode=1;}app.exit(process.exitCode||0);});
