'use strict';
// Explicit live integration check: native runtime/model requests, no microphone or voice sessions.
const {app,BrowserWindow,Menu}=require('electron'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
if(!process.argv.includes('--live'))throw Error('Pass --live to test the configured local agent accounts.');
app.getVersion=()=>require('../package.json').version;
const root=path.resolve(__dirname,'..'),out=path.join(root,'build/qa-runtime-app'),profile=path.join(out,'profile'),folder=path.join(out,'files');
fs.mkdirSync(folder,{recursive:true});fs.rmSync(profile,{recursive:true,force:true});fs.mkdirSync(profile+'/avatars',{recursive:true});app.setPath('userData',profile);
for(const slug of ['tia','sarah'])fs.symlinkSync(root+'/build/characters/'+slug,profile+'/avatars/'+slug);
fs.writeFileSync(profile+'/config.json',JSON.stringify({avatar:'tia',quality:'friendly',agentEnabled:true,agentAccess:'full',agentEngine:'hermes',agentFolder:folder,reasoningMode:'delegate',delegateProvider:'hermes',delegateAuth:'local_runtime',avatarAgentBindings:{tia:{hermes:'tia',openclaw:'main'},sarah:{hermes:'default',openclaw:'main'}}}));
const errors=[],templates=[];const buildMenu=Menu.buildFromTemplate;Menu.buildFromTemplate=function(t){templates.push(t);return buildMenu.call(this,t);};
app.on('browser-window-created',(_e,w)=>w.webContents.on('console-message',d=>{if(d.level==='error')errors.push(d.message);}));
const releases=require('../electron/releases.cjs');let releaseMode='available';releases.latestRelease=async()=>{if(releaseMode==='error')throw Error('Offline test');return {version:releaseMode==='available'?'0.2.10':'0.2.9',title:'A newer release',notes:'Verified test release',releaseURL:releases.RELEASES+'/tag/v0.2.10',downloadURL:releases.RELEASES+'/download/v0.2.10/GPT-Live.Avatar-0.2.10-arm64.dmg'};};
require('../electron/main.cjs');const wait=ms=>new Promise(r=>setTimeout(r,ms));async function until(fn,label){const end=Date.now()+180000;while(Date.now()<end){const v=await fn();if(v)return v;await wait(150);}throw Error('Timed out: '+label);}const run=(w,code)=>w.webContents.executeJavaScript('(async()=>{'+code+'})()');
app.whenReady().then(async()=>{try{
 const solo=await until(()=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/avatar.html')),'solo');await until(()=>run(solo,'return Boolean(window.gla_avatar?.resources.ready)'),'Tia');await run(solo,'await gla.openSettings()');
 const settings=await until(()=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/settings.html')),'settings');await until(()=>run(settings,"return Boolean(document.querySelector('[data-character=tia][data-engine=hermes]')?.options.length>1)"),'profile inventory');
 assert.equal(await run(settings,"return document.querySelector('[data-character=tia][data-engine=hermes]').value"),'tia');assert.equal(await run(settings,"return document.querySelector('[data-character=sarah][data-engine=hermes]').value"),'default');assert.equal(await run(settings,"return document.querySelector('#delegateAuth').disabled"),true);
 await run(settings,"await document.querySelector('#runtimeCheck').onclick()");assert.match(await run(settings,"return document.querySelector('#runtimeState').textContent"),/Hermes connected/);
 await run(settings,"document.querySelector('#agentBindings').closest('section').scrollIntoView({block:'start'})");await wait(200);fs.writeFileSync(out+'/agent-choices.png',(await settings.webContents.capturePage()).toPNG());
 const report=[];
 for(const engine of (process.argv.includes('--ui-only')?[]:['hermes','openclaw'])){
  console.log('Testing '+engine+' through the app…');await run(settings,`document.querySelector('#delegateProvider').value='${engine}';await document.querySelector('#delegateProvider').onchange();`);
  const reason=await run(solo,`return gla.delegate.answer({id:'${engine}-reason',history:[{role:'user',text:'What is seven times eight? Reply in one sentence.'}]})`);assert(reason.ok,reason.error);assert.equal(reason.engine,engine);assert.match(reason.text,/56|fifty.six/i);
  const file=engine+'-'+Date.now()+'.txt',request='Tia, use Python to create '+folder+'/'+file+' with exactly Tia verified. Read it back and report briefly.';
  const result=await run(solo,`return gla.agent.run(${JSON.stringify({id:engine+'-solo',history:[{role:'user',text:request}]})})`);assert(result.ok,result.error);assert.equal(result.engine,engine);assert.equal(result.agent,engine==='hermes'?'tia':'main');assert.equal(fs.readFileSync(folder+'/'+file,'utf8'),'Tia verified');
  await run(solo,'await gla.group.open()');const group=await until(()=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/group.html')),'Together');await until(()=>run(group,'return Boolean(window.gla_group&&!gla_group.state.loading)'),'cast');
  const request2='Sarah, read '+folder+'/'+file+' and create '+folder+'/sarah-'+file+' containing exactly Sarah verified. Then use the avatar endpoint to play your boxing warmup. Verify both tasks and answer briefly.';
  const result2=await run(group,`return gla.group.reply(${JSON.stringify({participants:['tia','sarah'],topic:'Verify the chosen agents',human:{enabled:true,name:'You'},history:[{speaker:'tia',text:result.text}],id:engine+'-group',turnId:engine+'-group',speaker:'sarah',humanRequest:request2})})`);assert(result2.ok,result2.error);assert.equal(result2.character,'Sarah');assert.equal(result2.agent,engine==='hermes'?'default':'main');assert.equal(result2.engine,engine);assert.equal(fs.readFileSync(folder+'/sarah-'+file,'utf8'),'Sarah verified');assert(result2.receipts.some(r=>r.tool==='play_motion'&&r.ok),JSON.stringify({text:result2.text,receipts:result2.receipts}));
  fs.writeFileSync(out+'/'+engine+'-group.png',(await group.webContents.capturePage()).toPNG());report.push({engine,reason:reason.text,solo:{text:result.text,agent:result.agent,model:result.model},group:{text:result2.text,agent:result2.agent,model:result2.model},verified:true});await run(group,'await gla.group.close()');
 }
 const menus=templates.flatMap(t=>t.flatMap(x=>x.submenu||[x]));const about=menus.find(x=>x.label==='About GPT-Live Avatar');assert(about);assert(menus.some(x=>x.label==='Check for Updates…'));about.click();const info=await until(()=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('/app-info.html')),'About');await until(()=>run(info,"return document.querySelector('#version')?.textContent==='Version 0.2.9'"),'version');
 assert.equal((await run(info,'return glaAppInfo.get()')).update.state,'idle');await run(info,"await document.querySelector('#check').onclick()");assert.equal((await run(info,'return glaAppInfo.get()')).update.state,'available');await until(()=>run(info,"return document.querySelector('#status').textContent==='Version 0.2.10 is available'"),'visible update');await wait(250);fs.writeFileSync(out+'/about.png',(await info.webContents.capturePage()).toPNG());
 releaseMode='current';await run(info,"await document.querySelector('#check').onclick()");assert.equal((await run(info,'return glaAppInfo.get()')).update.state,'current');releaseMode='error';await run(info,"await document.querySelector('#check').onclick()");assert.equal((await run(info,'return glaAppInfo.get()')).update.state,'error');
 await run(settings,"agentInventory={openclaw:{installed:false,agents:[]},hermes:{installed:false,agents:[]}};renderAgentBindings(SETTINGS)");assert.equal(await run(settings,"return [...document.querySelectorAll('#agentBindings select')].every(s=>s.disabled)"),true);await run(settings,"document.querySelector('#agentBindings').closest('section').scrollIntoView({block:'start'})");fs.writeFileSync(out+'/missing-runtimes.png',(await settings.webContents.capturePage()).toPNG());
 assert.deepEqual(errors,[]);fs.writeFileSync(out+(process.argv.includes('--ui-only')?'/ui-report.json':'/report.json'),JSON.stringify({passed:true,report,errors},null,2));console.log('Real Hermes and OpenClaw solo/Together requests, distinct profile routing, files, avatar motion receipts, agent dropdowns and About/update states passed.');
 }catch(e){console.error(e.stack);console.error(errors);process.exitCode=1;}finally{app.exit(process.exitCode||0);}});
