const {app,BrowserWindow}=require('electron'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const repo=path.resolve(__dirname,'..'),out=path.join(repo,'build/qa-skinning');fs.mkdirSync(out,{recursive:true});app.setPath('userData',out+'/profile');
const server=http.createServer((req,res)=>{let p=path.join(repo,'web',req.url);if(req.url==='/'){res.setHeader('Content-Type','text/html');return res.end('<title>Deformation test</title>');}res.setHeader('Content-Type','text/javascript');fs.createReadStream(p).pipe(res);});
app.whenReady().then(async()=>{try{await new Promise(r=>server.listen(0,'127.0.0.1',r));const w=new BrowserWindow({show:false,webPreferences:{backgroundThrottling:false}});const errors=[];w.webContents.on('console-message',d=>{if(d.level==='error')errors.push(d.message);});await w.loadURL('http://127.0.0.1:'+server.address().port);
const result=await w.webContents.executeJavaScript(`(async()=>{
const T=await import('/vendor/three/three.module.js'),{AvatarVolumeSkin}=await import('/avatar3d-volume.js');
const renderer=new T.WebGLRenderer();renderer.setSize(1,1);const scene=new T.Scene(),model=new T.Group();scene.add(model);
const geom=new T.BufferGeometry();geom.setAttribute('position',new T.Float32BufferAttribute([.5,.7,.2,.5,.7,.2,.5,.7,.2],3));geom.setAttribute('skinIndex',new T.Uint16BufferAttribute([0,1,0,0,0,1,0,0,0,1,0,0],4));geom.setAttribute('skinWeight',new T.Float32BufferAttribute([.5,.5,0,0,.5,.5,0,0,.5,.5,0,0],4));geom.setAttribute('pixel',new T.Float32BufferAttribute([-1,-1,3,-1,-1,3],2));
const mat=new T.ShaderMaterial({vertexShader:'attribute vec2 pixel;varying vec3 result;\\n#include <skinning_pars_vertex>\\nvoid main(){vec3 transformed=position;\\n#include <skinbase_vertex>\\n#include <skinning_vertex>\\nresult=transformed;gl_Position=vec4(pixel,0.,1.);}',fragmentShader:'varying vec3 result;void main(){gl_FragColor=vec4(result,1.);}',toneMapped:false});
const mesh=new T.SkinnedMesh(geom,mat),b0=new T.Bone(),b1=new T.Bone();mesh.userData.sourceName='DQTest';model.add(mesh,b0,b1);model.updateMatrixWorld(true);mesh.bind(new T.Skeleton([b0,b1]));mesh.frustumCulled=false;const volume=new AvatarVolumeSkin({model},['DQTest']);
const target=new T.WebGLRenderTarget(1,1,{type:T.FloatType,format:T.RGBAFormat,depthBuffer:false});const output=new Float32Array(4),camera=new T.PerspectiveCamera();const cases=[];
for(const [name,angle,scale] of [['rest',0,1],['opposing-quarter-turns',Math.PI/2,1],['near-half-turns',Math.PI*.97,1],['affine-fallback',.7,1.4]]){
 b0.quaternion.setFromAxisAngle(new T.Vector3(0,0,1),angle);b1.quaternion.setFromAxisAngle(new T.Vector3(0,0,1),-angle);b1.scale.set(scale,1,1);b0.position.set(.02,.01,.03);b1.position.set(-.02,-.01,-.03);model.updateMatrixWorld(true);mesh.skeleton.update();const cpu=mesh.getVertexPosition(0,new T.Vector3()).toArray();renderer.setRenderTarget(target);renderer.render(scene,camera);renderer.readRenderTargetPixels(target,0,0,1,1,output);const gpu=Array.from(output.slice(0,3));const error=Math.max(...cpu.map((x,i)=>Math.abs(x-gpu[i])));if(error>1e-5)throw Error(name+' CPU/GPU disagreement '+error);cases.push({name,cpu,gpu,error});
 if(name==='opposing-quarter-turns'&&Math.hypot(cpu[0]-.01,cpu[1]+.02)<.7)throw Error('Bend collapsed volume');
 if(name==='affine-fallback'){const original=new T.Vector3(.5,.7,.2);T.SkinnedMesh.prototype.applyBoneTransform.call(mesh,0,original);if(original.distanceTo(new T.Vector3(...cpu))>1e-6)throw Error('Affine fallback changed matrix skinning');}
}
volume.dispose();renderer.dispose();return cases;})()`);
assert.equal(errors.length,0,errors.join('\n'));fs.writeFileSync(out+'/report.json',JSON.stringify(result,null,2));console.log('GPU and CPU deformation agree; opposing rotations preserve volume; affine bones retain matrix skinning.',result.map(x=>x.error));
}catch(e){console.error(e);process.exitCode=1;}finally{server.close();app.exit(process.exitCode||0);}});
