const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{
 const source=fs.readFileSync(process.env.GLA_ZOOM_SOURCE||require('node:path').resolve(__dirname,'../web/avatar-zoom.js'),'utf8');
 const {zoomScale,zoomFit,zoomCrop,panCrop,pixelView}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
 const point={x:700,y:250},initial={scale:.35,x:510,y:-25};let fit=initial;
 const model={x:(point.x-fit.x)/fit.scale,y:(point.y-fit.y)/fit.scale};
 for(let i=0;i<20;i++)fit=zoomFit(fit,1.6,point,.12);
 assert(fit.scale>1000,'Gesture zoom greatly exceeds the old 1.25 cap');
 assert(Math.abs(fit.x+model.x*fit.scale-point.x)<1e-6);
 assert(Math.abs(fit.y+model.y*fit.scale-point.y)<1e-6);
 for(let i=0;i<20;i++)fit=zoomFit(fit,1/1.6,point,.12);
 assert(Math.abs(fit.scale-initial.scale)<1e-10,'Pinch out reverses zoom');
 let extreme=1;for(let i=0;i<10000;i++)extreme=zoomScale(extreme,1.2);
 assert(Number.isFinite(extreme)&&extreme>=999999&&extreme<=1000001);
 assert.equal(zoomScale(1,NaN),1);assert.equal(zoomScale(1,Infinity),1);
 const before={x:100,y:100,w:400,h:600},after={x:0,y:70,w:600,h:900},view={x:.2,y:.1,w:.4,h:.4};
 const enlarged=zoomCrop(view,before,after,point,100);
 assert(enlarged.w<.01,'Display-sized group frame continues zooming');
 const sourcePoint={x:view.x+(point.x-before.x)/before.w*view.w,y:view.y+(point.y-before.y)/before.h*view.h};
 assert(Math.abs(enlarged.x+(point.x-after.x)/after.w*enlarged.w-sourcePoint.x)<1e-12);
 assert(Math.abs(enlarged.y+(point.y-after.y)/after.h*enlarged.h-sourcePoint.y)<1e-12);
 const stretched={x:0,y:70,w:900,h:750},odd=zoomCrop(view,before,stretched,point,100);
 assert(Math.abs(odd.x+(point.x-stretched.x)/stretched.w*odd.w-sourcePoint.x)<1e-12);
 assert(Math.abs(odd.y+(point.y-stretched.y)/stretched.h*odd.h-sourcePoint.y)<1e-12);
 assert(Math.abs(odd.w/odd.h/(view.w/view.h)-(stretched.w/before.w)/(stretched.h/before.h))<1e-12);
 const pixels=pixelView(enlarged,800,1200);assert.equal(pixels.pixelWidth,800);assert.equal(pixels.pixelHeight,1200);
 const pan=panCrop(enlarged,60,-30,after);assert(pan.x<enlarged.x&&pan.y>enlarged.y);
 console.log('Deep zoom, pointer anchor, reversibility, finite projection and fixed render surface passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
