// Shared visible action log and request composer for solo and group windows.
export function installAgentUI({api,execute,onStatus=()=>{},interactive=()=>{},name=()=> 'Avatar'}){
 const cancelled=new Set();let requestId='',history=[],cancelledRequest='';
 const style=document.createElement('style');style.textContent=`.agent-dialog{width:min(480px,80vw);max-height:76vh;overflow:auto;border:1px solid #bbb8;border-radius:16px;padding:20px;color:#202126;background:#fafafa;font:14px/1.45 -apple-system,system-ui;box-shadow:0 12px 50px #0003}.agent-dialog::backdrop{background:#0002}.agent-dialog h2{font-size:18px;margin:0 0 12px}.agent-dialog textarea{box-sizing:border-box;width:100%;min-height:85px;font:inherit;border:1px solid #bbb;border-radius:8px;padding:10px}.agent-dialog button{border:1px solid #bbb;border-radius:8px;padding:8px 12px;background:white;font:inherit;cursor:pointer}.agent-dialog button:disabled{opacity:.5}.agent-dialog .agent-row{display:flex;gap:8px;margin-top:10px}.agent-dialog .agent-answer{white-space:pre-wrap;max-height:200px;overflow:auto;margin:12px 0}.agent-dialog .agent-note{font-size:12px;color:#666}.agent-dialog .agent-events{font-size:12px;overflow-wrap:anywhere;max-height:100px;overflow:auto}.agent-dialog .agent-state{margin-top:10px}`;document.head.append(style);
 const dialog=document.createElement('dialog');dialog.className='agent-dialog';dialog.innerHTML='<h2>Help with this</h2><p class="agent-note">Ask about the current browser page, create a text file, or direct a character. File destination: <span class="agent-folder"></span></p><textarea aria-label="Request" placeholder="Go to the upper-right corner and create a test file called tia.txt."></textarea><div class="agent-row"><button data-send>Ask</button><button data-page>Read this page</button><button data-stop disabled>Stop</button><button data-close>Close</button></div><div class="agent-state" role="status"></div><div class="agent-answer"></div><div class="agent-events"></div>';document.body.append(dialog);
 const get=s=>dialog.querySelector(s),state=get('.agent-state'),answer=get('.agent-answer'),events=get('.agent-events');
 const labels={avatar_state:'Checking installed motions',move_avatar:'Moving',play_motion:'Playing motion',read_current_page:'Reading the current page',read_webpage_url:'Reading the linked page',list_files:'Listing files',read_text_file:'Reading file',create_text_file:'Creating file'};
 const stop=()=>{cancelledRequest=requestId;if(requestId)void api.cancel(requestId);state.textContent='Stopped. Already completed file actions are kept.';requestId='';get('[data-send]').disabled=false;get('[data-page]').disabled=false;get('[data-stop]').disabled=true;};
 api.onAction(async({id,action,args})=>{try{const result=await execute(action,args,()=>cancelled.has(id));if(!cancelled.has(id))api.actionResult(id,result||{ok:true});}catch(e){api.actionResult(id,{ok:false,error:e.message});}finally{cancelled.delete(id);}});
 api.onCancel(({id})=>{cancelled.add(id);if(cancelled.size>64)cancelled.delete(cancelled.values().next().value);});
 api.onProgress(p=>{if(p.id===cancelledRequest)return;const message=p.state==='thinking'?'Working…':p.state==='complete'?(p.receipts?.some(r=>!r.ok)?'Finished with an issue':'Done'):p.state==='error'?p.error:(labels[p.tool]||p.tool)+(p.state==='done'?' · done':'…');onStatus(message);state.textContent=message;
  if(p.state==='complete'){answer.textContent=p.text||'';const receipts=p.receipts||[];events.replaceChildren(...receipts.filter(x=>x.path||x.url||x.error).map(x=>{const d=document.createElement('div');d.textContent=x.error||x.path||[x.title,x.url].filter(Boolean).join(' — ');return d;}));}
 });
 async function run(text){if(requestId||!text.trim())return;requestId='agent-'+crypto.randomUUID();const id=requestId;history.push({role:'user',text:text.trim()});history=history.slice(-12);get('[data-send]').disabled=true;get('[data-page]').disabled=true;get('[data-stop]').disabled=false;answer.textContent='';events.textContent='';
  let result;try{result=await api.run({id,history,turnId:id});}catch(e){result={ok:false,error:e.message};}if(requestId!==id)return;requestId='';get('[data-send]').disabled=false;get('[data-page]').disabled=false;get('[data-stop]').disabled=true;
  if(result.ok){answer.textContent=result.text;history.push({role:'assistant',text:result.text});}else{state.textContent=result.error;onStatus(result.error);}
 }
 get('[data-send]').onclick=()=>run(get('textarea').value);get('[data-page]').onclick=()=>{get('textarea').value='What do you think of this webpage? Read the current page and give me your assessment.';void run(get('textarea').value);};get('[data-stop]').onclick=stop;get('[data-close]').onclick=()=>dialog.close();
 dialog.addEventListener('close',()=>interactive(false));dialog.addEventListener('cancel',()=>interactive(false));get('textarea').addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.metaKey||e.ctrlKey)){e.preventDefault();void run(get('textarea').value);}});
 // Codex asks for missing input in the same visible surface in solo and
 // Together. Text content never becomes HTML, and closing means no answer.
 let questionDialog=null;
 api.onQuestion?.(request=>{
  questionDialog?.close();const d=document.createElement('dialog');questionDialog=d;d.className='agent-dialog';d.dataset.id=request.id;
  const title=document.createElement('h2');title.textContent=request.character+' has a question';d.append(title);const fields=[];
  for(const q of request.questions||[]){const label=document.createElement('p');label.textContent=q.question;d.append(label);const input=document.createElement('textarea');input.setAttribute('aria-label',q.question);if(q.options?.length){const choices=document.createElement('div');for(const option of q.options){const b=document.createElement('button');b.textContent=option.label;b.title=option.description||'';b.onclick=()=>input.value=option.label;choices.append(b);}d.append(choices);}d.append(input);fields.push({q,input});}
  const submit=document.createElement('button');submit.textContent='Send answer';submit.onclick=()=>{const answers=Object.fromEntries(fields.map(({q,input})=>[q.id,{answers:[input.value.trim()]}]));api.answerQuestion(request.id,answers);d.dataset.sent='true';d.close();};d.append(submit);
  d.onclose=()=>{if(!d.dataset.sent)api.answerQuestion(request.id,{});if(questionDialog===d)questionDialog=null;d.remove();interactive(false);};document.body.append(d);interactive(true);d.showModal();fields[0]?.input.focus();
 });
 api.onQuestionClose?.(({id})=>{if(questionDialog?.dataset.id===id){questionDialog.dataset.sent='true';questionDialog.close();}});
 return {open(settings){get('h2').textContent='Ask '+name();get('.agent-folder').textContent=settings.agentFolder||'Desktop';interactive(true);dialog.showModal();get('textarea').focus();},stop,dialog};
}
